version: '3'

services:
  flask:
    container_name: fourstory-flask
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=true
      - HOSTNAME=http://127.0.0.1
      - PORT=8080
    volumes:
      - ./:/app
    ports:
      - "8080:5000"
    command: flask run --host 0.0.0.0
    restart: on-failure
